[package]
name = "rust_vad"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ort = {version = "=2.0.0-rc.5", features = ["ndarray"]}
ndarray = "0.16"
hound = "3"
lazy_static = "1.5.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21.1"

[features]
default = []
android = []
ios = []
macos = []
